# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddcc75a5fa95b898c23cca605342c60996b84a95ea699fbcd4ef2cb3694471e10831529e957d608b6616fab5833ce63acf4f9523d4d4157ccb2ad0da2a1fa798

test:
  secret_key_base: d5cacdd0ba75c3378eb868179d5a592121d58d04cbf9a16282f5abfdbc9fe47b5d363ca6fd5d49b17c59bfd3a1d740e90d5aa10b9d8898b57e2d905af2bda7d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
